### ISSUE TITLE
Export to a spreadsheet produces an empty sheet

### ISSUE THREAD

**Issue by mwendwa5** [GibbonEdu/module-queryBuilder#2]
Export to spreadsheet produces an empty sheet. Any idea what the issue could be? I've attached relevant screenshot and file.
[queryBuilderExport.xlsx](https://github.com/GibbonEdu/module-queryBuilder/files/976226/queryBuilderExport.xlsx)
![selection_384](https://cloud.githubusercontent.com/assets/4364019/25705533/47598c82-30e6-11e7-9f2b-df568359023a.png)

**Comment by rossdotparker** [comment]
Hello, our wonderful @SKuipers has identified what she believes is the issue, and has put a fix in place. I have rolled this into a new release, v1.2.16, which you can download on our [extend page](https://gibbonedu.org/extend/). Let us know if this works. Ross.

**Comment by mwendwa5** [comment]
Thanks @rossdotparker @SKuipers. This works 👍
